apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-web
  labels:
    app: spring-boot-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-web
  template:
    metadata:
      labels:
        app: spring-boot-web
    spec:
      containers:
      - name: spring-boot-web
        image: techvault2024/spring-boot-web:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30