apiVersion: v1
kind: Service
metadata:
  name: spring-boot-web
  labels:
    app: spring-boot-web
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-web